<a href="https://colab.research.google.com/github/Sriram04r/CRT_2026/blob/main/LEET_CODE_PROBLEMS_%26_NUMPY's.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**LEET CODE PROBLEMS - 29-07-2026**

In [ ]:
matrix=[
    [1,2,3,4],
    [5,6,7,8],
    [9,10,11,12],
    [13,14,15,16]
    ]
n=len(matrix)
m=len(matrix[0])
sr=0
sc=0
er=n-1
ec=m-1
l=[]
while sr<=er and sc<=ec:
    for j in range(sc,ec+1):
        l.append(matrix[sr][j])
    for i in range(sr+1,er+1):
        l.append(matrix[i][ec])
    for j in range(ec-1,sc-1,-1):
        l.append(matrix[er][j])
    for i in range(er-1,sr,-1):
        l.append(matrix[i][sc])
    sr+=1
    er-=1
    sc+=1
    ec-=1
print(l)

[1, 2, 3, 4, 8, 12, 16, 15, 14, 13, 9, 5, 6, 7, 11, 10]


In [ ]:
class Solution:
    def spiralOrder(self, matrix):

        result = []

        top = 0
        bottom = len(matrix) - 1

        left = 0
        right = len(matrix[0]) - 1

        while top <= bottom and left <= right:

            for col in range(left, right + 1):
                result.append(matrix[top][col])
            top += 1

            for row in range(top, bottom + 1):
                result.append(matrix[row][right])
            right -= 1

            if top <= bottom:
                for col in range(right, left - 1, -1):
                    result.append(matrix[bottom][col])
                bottom -= 1

            if left <= right:
                for row in range(bottom, top - 1, -1):
                    result.append(matrix[row][left])
                left += 1

        return result
matrix = [
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
]

solution_obj = Solution()

result = solution_obj.spiralOrder(matrix)

print(result)


[1, 2, 3, 6, 9, 8, 7, 4, 5]


**MATRIX MULTIPLICAtION - 30-07-2026**

In [1]:
mat1=[
    [1,2,3],
    [4,5,6],
    [7,8,9]
    ]
mat2=[
    [1,2],
    [3,4],
    [5,6]
    ]
n1=len(mat1)
m1=len(mat1[0])
n2=len(mat2)
m2=len(mat2[0])

res=[]
for i in range(n1):
    l=[0]*m2
    res.append(l)
for i in range(n1):
    for j in range(m2):
        for k in range(m1):
            res[i][j]+=mat1[i][k]*mat2[k][j]
print(res)

[[22, 28], [49, 64], [76, 100]]


**NUMERICAL PYTHON - NUMPY(np)**

1. INITIALIZATION




In [2]:
import numpy as np
l = [123]
arr = np.array(l)
print(arr)

[123]


In [3]:
import numpy as np

arr = np.array([3,2,1])
print(arr)

[3 2 1]


In [10]:
import numpy as np

mat = np.zeros((3, 3))
print(mat)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [12]:
import numpy as np

mat = np.eye(3)
print(mat)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [14]:
import numpy as np

mat = np.full((2, 3), 5)
print(mat)

[[5 5 5]
 [5 5 5]]


In [17]:
import numpy as np

mat = np.arange(1, 11)
print(mat)

[ 1  2  3  4  5  6  7  8  9 10]


In [22]:
import numpy as np

mat = np.arange(1, 11, 2)
print(mat)


[1 3 5 7 9]


In [33]:
import numpy as np

mat1 = np.full((2, 3), 5)
mat2 = np.full((2, 3), 7)
print(mat1)
print(mat2)

[[5 5 5]
 [5 5 5]]
[[7 7 7]
 [7 7 7]]


In [32]:
import numpy as np

mat1 = np.full((2, 3), 5)
mat2 = np.full((2, 3), 7)
mat3 = (mat1) + (mat2)
print(mat3)

[[12 12 12]
 [12 12 12]]


In [36]:
import numpy as np

mat1 = np.array([[1,2,3], [4,5,6], [7,8,9]])
mat2 = np.array([[1,2], [3,4], [5,6]])
mat3 = np.matmul(mat1, mat2)
print(mat3)

[[ 22  28]
 [ 49  64]
 [ 76 100]]


In [40]:
import numpy as np

arr = np.array([1,2,3,4,5,6])
mat = arr.reshape((2,3))
print(arr)

[1 2 3 4 5 6]


In [ ]:
import numpy as np

mat1 = np.full((2, 3), 5)
mat2 = np.full((2, 3), 7)
print(mat1)
print(mat2)